# Generated by Django 5.2.8 on 2025-11-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alerte'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alerte',
            new_name='core_alerte_niveau_e6d7be_idx',
            old_name='core_alerte_niveau__363c6a_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_occurre_efd0d7_idx',
            old_name='core_auditl_occurre_43e90b_idx',
        ),
        migrations.RenameIndex(
            model_name='departement',
            new_name='core_depart_code_466985_idx',
            old_name='core_departe_code_272eed_idx',
        ),
        migrations.RenameIndex(
            model_name='departement',
            new_name='core_depart_name_b3a909_idx',
            old_name='core_departe_name_473ddf_idx',
        ),
        migrations.RenameIndex(
            model_name='programme',
            new_name='core_progra_departe_e61d40_idx',
            old_name='core_program_departe_e4e479_idx',
        ),
        migrations.RenameIndex(
            model_name='promotion',
            new_name='core_promot_program_5eecd9_idx',
            old_name='core_promoti_program_0a76fd_idx',
        ),
        migrations.RenameIndex(
            model_name='promotion',
            new_name='core_promot_start_d_6fb4b5_idx',
            old_name='core_promoti_start_d_a072c5_idx',
        ),
    ]
