# Generated by Django 5.2.8 on 2025-11-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campagne',
            new_name='offres_camp_start_d_e987c8_idx',
            old_name='offres_camp_start_d_31aaae_idx',
        ),
        migrations.RenameIndex(
            model_name='offrestage',
            new_name='offres_offr_status_1dd7d1_idx',
            old_name='offres_offr_status_0b02b3_idx',
        ),
        migrations.RenameIndex(
            model_name='offrestage',
            new_name='offres_offr_entrepr_49681e_idx',
            old_name='offres_offr_entrepr_ae0100_idx',
        ),
    ]
