# Generated by Django 5.2.8 on 2025-11-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactentreprise',
            new_name='entreprises_last_na_ee00de_idx',
            old_name='entreprise_last_na_3c5f47_idx',
        ),
        migrations.RenameIndex(
            model_name='contactentreprise',
            new_name='entreprises_email_f940e2_idx',
            old_name='entreprise_email_13e9c2_idx',
        ),
        migrations.RenameIndex(
            model_name='entreprise',
            new_name='entreprises_name_a21001_idx',
            old_name='entreprises_name_894421_idx',
        ),
        migrations.RenameIndex(
            model_name='entreprise',
            new_name='entreprises_contact_a7c541_idx',
            old_name='entreprises_contact__a76aac_idx',
        ),
    ]
