# Generated by Django 5.2.8 on 2025-11-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='affectation',
            new_name='affectation_status_d479fa_idx',
            old_name='affectatio_status__0614a8_idx',
        ),
        migrations.RenameIndex(
            model_name='affectation',
            new_name='affectation_entrepr_080858_idx',
            old_name='affectatio_entrepri_99f0e7_idx',
        ),
    ]
