# Generated by Django 5.2.8 on 2025-11-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Total étudiants')),
                ('total_offers', models.PositiveIntegerField(default=0, verbose_name='Total offres')),
                ('total_assignments', models.PositiveIntegerField(default=0, verbose_name='Total affectations')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': 'Instantané de reporting',
                'verbose_name_plural': 'Instantanés de reporting',
                'ordering': ('-generated_at',),
            },
        ),
    ]
