# Generated by Django 5.2.8 on 2025-11-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='candidature',
            new_name='candidature_status_680010_idx',
            old_name='candidat_status__e1f9f7_idx',
        ),
        migrations.RenameIndex(
            model_name='candidature',
            new_name='candidature_offer_i_ef311e_idx',
            old_name='candidat_offer_id_70c9b6_idx',
        ),
    ]
